import { Subject } from 'rxjs/Subject'
import { scan } from 'rxjs/operators'

export type Action = {
  type: string
  count?: number
}

export type ActionCreator = (...args: any[]) => Action
export type Dispatcher = (...args: any[]) => void

export const createStoreAndDispatch = (reducer: (state: {}, action: {}) => {}, initialState: {}) => {
  const action$ = new Subject()

  

  return {
    store$: action$.pipe(scan(reducer, initialState)),
    // todo -- could add other utility values here, which could then be run since they will be generated by the file
    dispatch: (fn: ActionCreator): Dispatcher => (...args: any[]) =>
      action$.next(fn(...args)),
  }
}
